### ISSUE TITLE
Record Manager cannot be saved twice

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager#27]
Tested on https://github.com/kbss-cvut/23ava-distribution with internal authorization.

**Comment by blcham** [comment]
I get following error:
```
ava-record-manager-server  | 01-12-2023 07:27:43.969 [] [http-nio-8080-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/record-manager] threw exception [Request processing failed: cz.cvut.kbss.jopa.exceptions.OWLEntityExistsException: Individual <http://onto.fel.cvut.cz/ontologies/record-manager/patient-record/1475946137332283125> is already managed in the persistence context.] with root cause
ava-record-manager-server  | cz.cvut.kbss.jopa.exceptions.OWLEntityExistsException: Individual <http://onto.fel.cvut.cz/ontologies/record-manager/patient-record/1475946137332283125> is already managed in the persistence context.
ava-record-manager-server  |    at cz.cvut.kbss.jopa.exceptions.OWLEntityExistsException.individualAlreadyManaged(OWLEntityExistsException.java:29)
ava-record-manager-server  |    at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.getManagedClone(UnitOfWorkImpl.java:180)
ava-record-manager-server  |    at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.readManagedObject(UnitOfWorkImpl.java:171)
ava-record-manager-server  |    at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.readObjectInternal(UnitOfWorkImpl.java:148)
ava-record-manager-server  |    at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.readObject(UnitOfWorkImpl.java:141)
ava-record-manager-server  |    at cz.cvut.kbss.jopa.model.EntityManagerImpl.find(EntityManagerImpl.java:289)
ava-record-manager-server  |    at com.github.ledsoft.jopa.spring.transaction.DelegatingEntityManager.find(DelegatingEntityManager.java:80)
ava-record-manager-server  |    at cz.cvut.kbss.study.persistence.dao.PatientRecordDao.update(PatientRecordDao.java:91)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ava-record-manager-server  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
ava-record-manager-server  |    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
ava-record-manager-server  |    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
ava-record-manager-server  |    at cz.cvut.kbss.study.persistence.dao.PatientRecordDao$$SpringCGLIB$$0.update(<generated>)
ava-record-manager-server  |    at cz.cvut.kbss.study.service.repository.BaseRepositoryService.update(BaseRepositoryService.java:60)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ava-record-manager-server  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
ava-record-manager-server  |    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
ava-record-manager-server  |    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
ava-record-manager-server  |    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
ava-record-manager-server  |    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
ava-record-manager-server  |    at cz.cvut.kbss.study.service.repository.RepositoryPatientRecordService$$SpringCGLIB$$0.update(<generated>)
ava-record-manager-server  |    at cz.cvut.kbss.study.rest.PatientRecordController.updateRecord(PatientRecordController.java:84)
ava-record-manager-server  |    at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ava-record-manager-server  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
ava-record-manager-server  |    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
ava-record-manager-server  |    at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:199)
ava-record-manager-server  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
ava-record-manager-server  |    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
ava-record-manager-server  |    at cz.cvut.kbss.study.rest.PatientRecordController$$SpringCGLIB$$0.updateRecord(<generated>)
ava-record-manager-server  |    at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
ava-record-manager-server  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ava-record-manager-server  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
ava-record-manager-server  |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
ava-record-manager-server  |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
ava-record-manager-server  |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
ava-record-manager-server  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
ava-record-manager-server  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
ava-record-manager-server  |    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
ava-record-manager-server  |    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
ava-record-manager-server  |    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
ava-record-manager-server  |    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
ava-record-manager-server  |    at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:925)
ava-record-manager-server  |    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:593)
ava-record-manager-server  |    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
ava-record-manager-server  |    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
ava-record-manager-server  |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
ava-record-manager-server  |    at cz.cvut.kbss.study.rest.servlet.DiagnosticsContextFilter.doFilter(DiagnosticsContextFilter.java:51)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
ava-record-manager-server  |    at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
ava-record-manager-server  |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
ava-record-manager-server  |    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
ava-record-manager-server  |    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at cz.cvut.kbss.study.security.CsrfHeaderFilter.doFilterInternal(CsrfHeaderFilter.java:36)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
ava-record-manager-server  |    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
ava-record-manager-server  |    at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
ava-record-manager-server  |    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
ava-record-manager-server  |    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
ava-record-manager-server  |    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
ava-record-manager-server  |    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
ava-record-manager-server  |    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
ava-record-manager-server  |    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
ava-record-manager-server  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
ava-record-manager-server  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
ava-record-manager-server  |    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
ava-record-manager-server  |    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
ava-record-manager-server  |    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
ava-record-manager-server  |    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
ava-record-manager-server  |    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
ava-record-manager-server  |    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
ava-record-manager-server  |    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
ava-record-manager-server  |    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
ava-record-manager-server  |    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
ava-record-manager-server  |    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
ava-record-manager-server  |    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
ava-record-manager-server  |    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
ava-record-manager-server  |    at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
ava-record-manager-server  |    at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
ava-record-manager-server  |    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ava-record-manager-server  |    at java.base/java.lang.Thread.run(Thread.java:840)
```
